App\Entity\Product\ProductCompleteInfoTranslation:
    properties:
        content:
            - App\Validator\CMSContentConstraint\ProductCompleteInfoContent:
                groups: [sylius]
            - Type:
                type: string
                groups: [sylius]
            - NotBlank:
                groups: [sylius]
