services:
    App\Promotion\Action\FixedDiscountPromotionActionCommand:
        decorates: sylius.promotion_action.fixed_discount
        autowire: true
        autoconfigure: true

    sylius.promotion_action.percentage_discount:
        class: App\Promotion\Action\OrderPercentageDiscountCommand
        autowire: true
        tags:
            - { name: sylius.promotion_action, type: !php/const App\Promotion\Action\OrderPercentageDiscountCommand::TYPE, label: sylius.form.promotion_action.order_percentage_discount, form_type: Sylius\Bundle\PromotionBundle\Form\Type\Action\PercentageDiscountConfigurationType }

    sylius.promotion_action.unit_percentage_discount:
        class: App\Promotion\Action\UnitPercentageDiscountPromotionActionCommand
        arguments:
            - '@sylius.factory.adjustment'
            - '@sylius.promotion_filter.price_range'
            - '@sylius.promotion_filter.taxon'
            - '@sylius.promotion_filter.product'
        tags:
            - { name: sylius.promotion_action, type: unit_percentage_discount, label: sylius.form.promotion_action.item_percentage_discount, form_type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Action\ChannelBasedUnitPercentageDiscountConfigurationType }

    App\Promotion\Action\OrderPercentageOfFrontItemsDiscountCommand:
        autowire: true
        tags:
            - { name: sylius.promotion_action, type: !php/const App\Promotion\Action\OrderPercentageOfFrontItemsDiscountCommand::TYPE, label: sylius.form.promotion_action.order_percentage_of_front_items_discount, form_type: App\Form\Type\Action\OrderPercentageOfFrontItemsConfigurationType }
