imports:
    - { resource: '@SyliusCoreBundle/Resources/config/app/config.yml' }
    - { resource: '@SyliusAdminBundle/Resources/config/app/config.yml' }
    - { resource: '@SyliusAdminApiBundle/Resources/config/app/config.yml' }
    - { resource: '@SyliusApiBundle/Resources/config/app/config.yaml' }
    - { resource: '@SyliusShopBundle/Resources/config/app/config.yml' }
    - { resource: '@SyliusPayPalPlugin/Resources/config/config.yaml' }
    - { resource: '@SetonoSyliusAnalyticsPlugin/Resources/config/app/config.yaml' }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'
    
sylius_fixtures: ~

sylius_grid:
    templates:
        action:
            update_pages_positions: 'Admin/Page/Actions/updatePositions.html.twig'
            export_custom_orders: 'Admin/Order/Actions/exportCustomOrders.html.twig'

sylius_admin:
    notifications:
        enabled: false

sylius_addressing:
    resources:
        address:
            classes:
                model: App\Entity\Addressing\Address
        country:
            classes:
                model: App\Entity\Addressing\Country
        province:
            classes:
                model: App\Entity\Addressing\Province
        zone:
            classes:
                model: App\Entity\Addressing\Zone
        zone_member:
            classes:
                model: App\Entity\Addressing\ZoneMember

sylius_admin_api:
    resources:
        api_client:
            classes:
                model: App\Entity\AdminApi\Client
        api_access_token:
            classes:
                model: App\Entity\AdminApi\AccessToken
        api_refresh_token:
            classes:
                model: App\Entity\AdminApi\RefreshToken
        api_auth_code:
            classes:
                model: App\Entity\AdminApi\AuthCode

sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: App\Entity\Product\ProductAttribute
                translation:
                    classes:
                        model: App\Entity\Product\ProductAttributeTranslation
            attribute_value:
                classes:
                    model: App\Entity\Product\ProductAttributeValue
                    repository: App\Repository\Product\ProductAttributeValueRepository

sylius_channel:
    resources:
        channel:
            classes:
                model: App\Entity\Channel\Channel
                repository: App\Repository\Channel\ChannelRepository
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Product\ProductImage
        taxon_image:
            classes:
                model: App\Entity\Taxonomy\TaxonImage
        product_taxon:
            classes:
                model: App\Entity\Product\ProductTaxon
        channel_pricing:
            classes:
                model: App\Entity\Channel\ChannelPricing

sylius_currency:
    resources:
        currency:
            classes:
                model: App\Entity\Currency\Currency
        exchange_rate:
            classes:
                model: App\Entity\Currency\ExchangeRate

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Customer\Customer
        customer_group:
            classes:
                model: App\Entity\Customer\CustomerGroup

sylius_locale:
    resources:
        locale:
            classes:
                model: App\Entity\Locale\Locale

sylius_order:
    resources:
        order:
            classes:
                model: App\Entity\Order\Order
        order_item:
            classes:
                controller: App\Controller\Resource\OrderItemController
                model: App\Entity\Order\OrderItem
        order_item_unit:
            classes:
                model: App\Entity\Order\OrderItemUnit
        adjustment:
            classes:
                model: App\Entity\Order\Adjustment
        order_sequence:
            classes:
                model: App\Entity\Order\OrderSequence

sylius_payment:
    resources:
        payment_method:
            classes:
                model: App\Entity\Payment\PaymentMethod
            translation:
                classes:
                    model: App\Entity\Payment\PaymentMethodTranslation
        payment:
            classes:
                model: App\Entity\Payment\Payment
                repository: App\Repository\Payment\PaymentRepository

sylius_payum:
    resources:
        payment_security_token:
            classes:
                model: App\Entity\Payment\PaymentSecurityToken
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig

sylius_product:
    resources:
        product:
            classes:
                repository: App\Repository\Product\ProductRepository
                model: App\Entity\Product\Product
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
        product_variant:
            classes:
                repository: App\Repository\Product\ProductVariantRepository
                model: App\Entity\Product\ProductVariant
            translation:
                classes:
                    model: App\Entity\Product\ProductVariantTranslation
        product_option:
            classes:
                repository: App\Repository\Product\ProductOptionRepository
                model: App\Entity\Product\ProductOption
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionTranslation
        product_option_value:
            classes:
                repository: App\Repository\Product\ProductOptionValueRepository
                model: App\Entity\Product\ProductOptionValue
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionValueTranslation
        product_association:
            classes:
                model: App\Entity\Product\ProductAssociation
        product_association_type:
            classes:
                model: App\Entity\Product\ProductAssociationType
            translation:
                classes:
                    model: App\Entity\Product\ProductAssociationTypeTranslation

sylius_promotion:
    resources:
        promotion:
            classes:
                model: App\Entity\Promotion\Promotion
                repository: App\Repository\Promotion\PromotionRepository
        promotion_rule:
            classes:
                model: App\Entity\Promotion\PromotionRule
        promotion_action:
            classes:
                model: App\Entity\Promotion\PromotionAction
        promotion_coupon:
            classes:
                model: App\Entity\Promotion\PromotionCoupon

sylius_review:
    resources:
        product:
            review:
                classes:
                    model: App\Entity\Product\ProductReview

sylius_shipping:
    resources:
        shipment:
            classes:
                model: App\Entity\Shipping\Shipment
        shipping_method:
            classes:
                model: App\Entity\Shipping\ShippingMethod
            translation:
                classes:
                    model: App\Entity\Shipping\ShippingMethodTranslation
        shipping_category:
            classes:
                model: App\Entity\Shipping\ShippingCategory

sylius_taxation:
    resources:
        tax_category:
            classes:
                model: App\Entity\Taxation\TaxCategory
        tax_rate:
            classes:
                model: App\Entity\Taxation\TaxRate

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
                repository: App\Repository\Taxon\TaxonRepository
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser
        shop:
            user:
                classes:
                    model: App\Entity\User\ShopUser
        oauth:
            user:
                classes:
                    model: App\Entity\User\UserOAuth

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - '%kernel.project_dir%/themes'

winzou_state_machine:
    sylius_order_shipping:
        transitions:
            revert_cart:
                from: [ready]
                to: cart

    sylius_order_payment:
        transitions:
            revert_cart:
                from: [awaiting_payment]
                to: cart
        callbacks:
            after:
                generate_sample_promotion_on_paid:
                    on: ['pay']
                    do: ['@App\Promotion\Generator\PromotionSampleGenerator', 'generateSamplePromotionForUser']
                    args: ['object']
                send_mail_confirmation_on_paid:
                    on: ['pay']
                    do: ['@sylius.email_manager.order', 'sendConfirmationEmail']
                    args: ['object']

    sylius_order_checkout:
        transitions:
            revert_cart:
                from: [completed]
                to: cart
        callbacks:
            after:
                app_update_delivery_date:
                    on: ['complete']
                    do: ['@App\Checkout\Delivery\UpdateDateDelivery', 'updateMinMaxDelays']
                    args: ['object']

    sylius_order:
        transitions:
            revert_cart:
                from: [new]
                to: cart
        callbacks:
            after:
                ### revert an awaiting payment order to cart state callbacks ###
                app_cancel_reverted_order_payment:
                    on: ['revert_cart']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getLastPayment()', 'event', 'revert_cart', 'sylius_payment']
                app_revert_order_checkout_to_cart:
                    on: ['revert_cart']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', 'revert_cart', 'sylius_order_checkout']
                app_revert_order_payment_to_cart:
                    on: ['revert_cart']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', 'revert_cart', 'sylius_order_payment']
                app_revert_order_shipping_to_cart:
                    on: ['revert_cart']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', 'revert_cart', 'sylius_order_shipping']
                app_revert_order_to_cart_date_updater:
                    on: ['revert_cart']
                    do: ['@App\Processor\Order\RevertToCartDatesProcessor', 'process']
                    args: ['object']
                app_revert_order_to_cart_session:
                    on: ['revert_cart']
                    do: ['@App\Processor\Order\OrderToCartSessionProcessor', 'process']
                    args: ['object']
                app_revert_order_sample_promotion_to_cart:
                    on: ['revert_cart']
                    do: ['@App\Promotion\Remover\PromotionSampleRemover', 'decrementPromotionUsage']
                    args: ['object']

    sylius_payment:
        transitions:
            revert_cart:
                from: [new]
                to: cart
