sentry:
    dsn: '%env(SENTRY_DSN_BACK)%'
    options:
        environment: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException
                    - Symfony\Component\Console\Exception\CommandNotFoundException
                    - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
                    - Symfony\Component\HttpKernel\Exception\BadRequestHttpException
                    - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - Symfony\Component\Serializer\Exception\NotNormalizableValueException
                    - Symfony\Component\Validator\Exception\ConstraintDefinitionException

twig:
    globals:
        SENTRY_DSN_JAVASCRIPT: '%env(SENTRY_DSN_FRONT)%'
