app_admin_ajax_product_ikea_autocomplete:
    path: /autocomplete
    methods: [GET]
    defaults:
        _controller: app.controller.product_ikea:indexAction
        _format: json
        _sylius:
            serialization_groups: [Default]
            permission: true
            repository:
                method: getByCodeOrName
                arguments:
                    locale: !php/const App\Entity\Locale\Locale::DEFAULT_LOCALE_CODE
                    term: $term
                    limit: 50
